# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d13e334597786c9538a37396b6b794c2fbcedc55fb8e9cf8445c60968683b66f1ba9b6d9ededbc5e946b83eefcee180d556348f2a877afbd726258c2ecad22c

test:
  secret_key_base: 549c4602b4c4fcfb71297521e85d592fd3d080650fdc5a0db0e4a8d2daedc4af8b3dac8b4c524f5203c17029a8396aff35f3e7357d302af92bb7eff24aa011db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
